language: python
python:
  - "2.7"
env:
  - DJANGO=django==1.6.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q -r test_requirements.txt --use-mirrors
script: 
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
  - coverage run --source words runtests.py
  - coverage report
after_success: coveralls
