language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: pip install -r test_requirements.txt --use-mirrors
script: python words/tests/runtests.py
