language: python
python:
  - "2.7"
env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=django==1.6.2
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q -r test_requirements.txt --use-mirrors
script: 
  - coverage run --source words runtests.py
  - coverage report
after_success: coveralls
